apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testgoprj 
  janus-idp.io/tekton: testgoprj
  backstage.io/kubernetes-id: testgoprj
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgoprj
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  