apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testgoprj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testgoprj 
  name: testgoprj
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testgoprj 
